name: CI v2

on: [push, pull_request]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mvcaaa/localtunnel-server
        tags: ${{ github.sha }}, latest
        dockerfile: Dockerfile.server
    - uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: mvcaaa/localtunnel-client
        tags: ${{ github.sha }}, latest
        dockerfile: Dockerfile.client
