name: CI v2

on: [push, pull_request]

jobs:
  server-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        dockerfile: ./Dockerfile.server
        username: _json_key
        password: ${{ secrets.DOCKER_PASSWORD }}
        registry: gcr.io
        repository: enkora-public/localtunnel-server
        tags: ${{ github.sha }}, latest
  client-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: docker/build-push-action@v1
      with:
        dockerfile: ./Dockerfile.client
        username: _json_key
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: enkora-public/localtunnel-client
        tags: ${{ github.sha }}, latest
